spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never