spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  profiles:
    default: dev
  liquibase:
    change-log: classpath:db/master.xml
  sql:
    init:
      mode: never
jws:
  sharedKey: bdc6e4de-a1b9-49d4-bdec-39c2f0c62261